### ISSUE TITLE
[Windows] Unregister requires hotkey press to complete

### ISSUE THREAD

**Issue by ventsislav-georgiev** [golang-design/hotkey#10]
I hit this issue and then I saw that it is noted in the code: https://github.com/golang-design/hotkey/blob/258b6bcabcc202a0c4f03948aa776f6462f6bc1a/hotkey_windows.go#L82

Posting here for visibility.

**Comment by changkun** [comment]
https://github.com/golang-design/hotkey/releases/tag/v0.3.0 should have resolved all observable issues.

**Comment by ventsislav-georgiev** [comment]
Thanks! Properly unregisters now for Windows.

On another note, I noticed that on Mac the runOnMain for register is no longer required. The hotkeys can be registered from any goroutine. I guess the proposal in the fyne repo is redundant then?

**Comment by changkun** [comment]
> I guess the proposal in the fyne repo is redundant then?

That's not true. The proposal can also help platforms such as iOS or Android, which are not covered in our case. Any calls that require mainthread, not necessarily on macOS, could benifit from that.
