### ISSUE TITLE
Feature Request: Translate String to HotKey

### ISSUE THREAD

**Issue by HuakunShen** [golang-design/hotkey#18]
I have a very simple feature request: implement a map or function to translate string to a hotkey. 

This is very helpful when we use a custom hotkey configuration.

**Comment by changkun** [comment]
I think this feature has been discussed before, and we don't do it because the string-key mapping is not always bijective. See #14.

For a user of this package, one can always maintain the desired string to hotkey map themselves.

**Comment by changkun** [comment]
Based on the previous discussion, this is obsolete.
