### ISSUE TITLE
ERROR: hotkey: xxx is registered

### ISSUE THREAD

**Issue by OlegGulevskyy** [golang-design/hotkey#19]
I am trying to use this library with `wails` GUI library and everytime I get the error message that a hotkey is registered
![image](https://user-images.githubusercontent.com/43781031/203775150-90566566-747e-4d66-a5b0-92caec572ddb.png)
```
ERROR: hotkey: 109+4+1 is registered

X Error of failed request:  BadAccess (attempt to access private resource denied)
  Major opcode of failed request:  33 (X_GrabKey)
  Serial number of failed request:  10
  Current serial number in output stream:  11

exit status 1

```
no matter which key I am using with any modifier
not even sure where to look for some additional debuggin info, would you have any advice / help?

**Comment by changkun** [comment]
I think this is a known issue, see #11

**Comment by OlegGulevskyy** [comment]
So this means that there is no solution currently? Sorry I am far from familiar with native terms, so hard to understand the conclusion from the linked issue

**Comment by changkun** [comment]
The reason for having this error is that someone else had registered this hotkey combination already. To solve it, guarantee the key combination does not conflict with others.

I think @ventsislav-georgiev worked on potential solutions before, but we have not converged to a satisfactory solution yet.

**Comment by OlegGulevskyy** [comment]
So this means that if some app, somewhere somehow assigned a key bind and this app is not even active anymore / not listening for key use, this lib won't be able to use this shortcut anyway? Because I am assigning completely "random" shortcut making sure it is not used (when I use it nothing happens), it still returns an error

**Comment by changkun** [comment]
I think if you already grabbed the combination for your application successfully, future registration won't impact your registration anymore.

I don't entirely sure how you did random shortcuts, but I am pretty confident that some combination will work. Otherwise, it should be a system issue rather than the library itself.

**Comment by OlegGulevskyy** [comment]
Actually it was totally my bad, I was misusing the library - instantiating it in the wrong place of execution :) Thank you for your help though!
