### ISSUE TITLE
Is there an API to add new keys across platforms?

### ISSUE THREAD

**Issue by xeijin** [golang-design/hotkey#2]
I want to use a backtick/grave (`), but I want it to work across all platforms, how do I achieve this? Thanks.

**Comment by changkun** [comment]
Hi, we don't have such a feature at the moment. But you can pass the correct key code into the existing API. Let's say if the key code is 0x15, then you could cast the number into a Key type via `hotkey.Key(0x15)`, then using it as a parameter to call the `Register` function.  See:

https://github.com/golang-design/hotkey/blob/2997bd257bca1a9b2886e616a5a167c3138b5962/hotkey_windows.go#L71-L76
https://github.com/golang-design/hotkey/blob/2997bd257bca1a9b2886e616a5a167c3138b5962/hotkey.go#L72

**Comment by xeijin** [comment]
This works great for me, thanks very much.
