### ISSUE TITLE
Can multiple hotkeys be registered at the same time?

### ISSUE THREAD

**Issue by ficapy** [golang-design/hotkey#3]
For example, listening to Ctrl+1 and Ctrl+2 at the same time. 
my test failed on OSX, is this not allowed, or is it used incorrectly?

```golang
package main

import (
	"context"
	"golang.design/x/hotkey"
	"golang.design/x/mainthread"
)

func register(tag chan bool, mods []hotkey.Modifier, k hotkey.Key, output string) {
	go func() {
		hk, err := hotkey.Register(mods, k)
		if err != nil {
			panic("hotkey registration failed")
		}
		triggered := hk.Listen(context.Background())
		<-tag
		for range triggered {
			println("hotkey", output)
		}
	}()
}

func fn() {
	c := make(chan bool, 1)
	c <- true
	register(c, []hotkey.Modifier{hotkey.ModCtrl}, hotkey.Key1, "1")
	c <- true
	register(c, []hotkey.Modifier{hotkey.ModCtrl}, hotkey.Key2, "2")
}

func main() {
	mainthread.Init(fn)
}

```

**Comment by changkun** [comment]
Indeed, this is an implementation issue. When we start the call `Listen`, the handling must register a background application, making the current implementation not support registering multiple hotkeys. I will investigate this, and see if there are any workaround to realize it.

**Comment by changkun** [comment]
Moreover, this is also a platform-specific issue. I think it only occurs in macOS.

**Comment by changkun** [comment]
Sorry for the confusion. I think there is a flaw in your example. The current implementation already supports registering multiple hotkeys. See here is a complete example for registering multiple hotkeys:

https://github.com/golang-design/hotkey/blob/main/hotkey_darwin_test.go

**Comment by changkun** [comment]
Nothing needs to do here. Close.
