### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by eofreternal** [golang-design/hotkey#6]
I want to make an autoclick in Go. Looking through you readme, i still dont understand how to use it and what everything is for.
Please update your documention for clarity

(also, what does `for range triggered` do? why `for range` and not `if triggered`

**Comment by changkun** [comment]
Sorry because I can't help you if you are not even familiar with the language itself. Close.

**Comment by eofreternal** [comment]
@changkun I am only a beginner. If you wont exsplain it to me, how will I learn new concepts? How will i make projects? Golang AuotClicker seems small enough for my scope

**Comment by changkun** [comment]
There are many resource to learn: https://go.dev/doc/effective_go

**Comment by eofreternal** [comment]
no, i mean how to use your hotkey package

**Comment by changkun** [comment]
The document is clear enough. Use it or leave it. Thanks.
